---
title: "Oefeningen hoofdstuk 2 - het onderzoeksproces"
author: "Tijs Martens"
date: "6 maart 2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# oefening 2.1. 

Probeer nu vertrekkende van de niet-wetenschappelijke methode en weteschappelijke mthode manier aan te tonen dat varkens kunnen vliegen.

## niet- wetenschappelijke

een vogel is een een dier en kan vliegen een varken is ook een dier.

een vogel heeft slechts 2 poten en kan vliegen. Een varken heeft er 4 dus moet zeker ook kunnen vliegen.

## wetenschappelijk

We nemen 10 varkens mee naar de top van het empire state building. We gooien ze een voor een van de top en kijken als ze dit overleven en hoe ze reageren.





# oefening 2.2. 

**nominaal**: 
welke hobby's doe je?

* gamen
* sport
* andere


**ordinaal**:
hoe goed ging je examen?

* 1
* 2 
* 3 
* 4 
* 5

**intervalniveau**:
Hoeveel graden is het?

**rationiveau**:
Wat was je score op de test?


# oefening 2.3.

## Wat is de doelstelling van het onderzoek?

Te weten komen welk type databank de beste optie is voor het ontwikkelen van een mobiele applicaties

## Wie is het publiek?

Ontwikkelaars die applicaties maken, die ook offline moeten werken, voor mobiele toestellen

## Worden de conclussies expliciet gemaakt?

Ja, er wordt vemeld in welke situatie welke databasetechnologie de beste optie is.

## Schets kort hoe de structuur van het document in elkaar zit. Komt dit overeen met wat we gezien hebben.

**in de tekst**

1. inleiding: probleem uitleggen
2. uitleg over onderzoek
3. resultaten


**volgens cursus**

1. formuleren probleemstelling 
2. spcifiëren welke data we nodig hebben
3. uitvoeren onderzoek
4. verwerken van de gegevens
5. analyseren van de gegevens
6. formuleren van een conclusie




# oefening 2.4. 

**Context**

"applicaties moeten offline kunnen werken..."


**Nood**

"Als een applicatie niet offline kan werken, zal deze users verziezen..."

**Taak**

????

**Object**

????

**Resultaat**

weinig data: Realm
gemiddelde hoeveelheid data: Realm
veel data: SQLite

**Conclusie**

Het hangt af van het type applicatie welke technologie het meest efficiënt is. 

**Perspectief**

????
