---
title: "Oefening 3.7"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Opgave

Beschouw de volgende datasets uit het data frame "ais" (uit de library DAAG)

1. Ontleed de gegevens voor de roeiers
2. ontleed de gegevens voor de roeiers, netballers en de tennissers
3. ontleed de gegeven svoor de vrouwelijke besketballers en roeiers

```{r, echo=FALSE}
# install.packages(c("DAAG", "lattice"))
library(DAAG)
```

# Oplossing

## 1

```{r 1}
data <- subset(DAAG::ais, sport=="Row")
data
myvars <- c("ht") # we maken gebruik van de lengte van de spelers ter voorbeeld
newdata <- data[myvars]
summary(newdata)
```

## 2

```{r 2}
data <- subset(DAAG::ais, sport=="Row" | sport=="Netball" | sport=="Tennis")
data
myvars <- c("ht") # we maken gebruik van de lengte van de spelers ter voorbeeld
newdata <- data[myvars]
summary(newdata)
```

## 3

```{r 3}
data <- subset(DAAG::ais, (sport=="Row" | sport=="B_Ball") & sex =="f")
data
myvars <- c("ht") # we maken gebruik van de lengte van de spelers ter voorbeeld
newdata <- data[myvars]
summary(newdata)
```
